host: [domain.com]
host_port: 443
port: 9531 # This is tge standard port for the exporter
api_key: {apikey}
https: true
ignore_ssl: false
# Can be set to `admin-all` (return all servers), `owner` (only owned servers)
# or "" (only accessible servers, shown in your servers list)
server_list_type: ""
query_interval: 10
# Interval in seconds between each query to the Pterodactyl panel (default: 10)